### ISSUE TITLE
duckdb-rs 0.8.x breaks when loading extentions

### ISSUE THREAD

**Issue by a-agmon** [duckdb/duckdb-rs#203]
The following code fails when updating to duckdb v 0.8.1 with:

```
Assertion failed: (dynamic_cast<TARGET *>(this)), function Cast, file parse_info.hpp, line 22.
[1]    41517 abort      cargo run
```

when versions 0.7.x worked with no problem.

```rust 
use duckdb::arrow::record_batch::RecordBatch;
use duckdb::arrow::util::pretty::print_batches;
use duckdb::{params, Connection, Result};

fn main() -> Result<()> {
    let conn = Connection::open_in_memory()?;
    conn.execute_batch("INSTALL parquet; LOAD parquet;")?;

    Ok(())
}

```

```toml
[package]
name = "ddb-test-rust"
version = "0.1.0"
edition = "2021"

[dependencies.duckdb]
version = "0.8.0"
features = ["bundled"]

```

running using latest Rust on MacOS 1 (M1) ARM
