### ISSUE TITLE
SIGSEGV when reading geometry

### ISSUE THREAD

**Issue by lringham** [duckdb/duckdb-rs#486]
I am attempting to use `ST_Read` to read geometry and am receiving a `SIGSEGV` error.

I've attempted it using relative and absolute paths, as well as `shp`, and `geojson` files.
The duckdb versions I have tried are: `1.2.1, 1.2.0,` and `1.1.1`

`src/main.rs`
```rs
use duckdb::{Connection, Result};

fn main() -> Result<()> {
    let conn = Connection::open_in_memory()?;
    let query = r#"install spatial; load spatial;"#;
    if let Err(_) = conn.execute_batch(query) {
        print!("Error installing or loading spatial!");
    }

    let query = r#"SELECT * FROM ST_Read('map.geojson');"#;
    let _stmt = conn.prepare(query)?;

    Ok(())
}
```
`Cargo.toml`
```toml
[package]
name = "dbtest"
version = "0.1.0"
edition = "2024"
authors = []

[dependencies]
duckdb = { version = "1.2.1", features = ["bundled"] }
```
`map.geojson`
```
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"coordinates":[26.381510199595084,10.761477054604754],"type":"Point"}}]}
```
output of `cargo run`
```
   Compiling dbtest v0.1.0
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 6.61s
     Running `target/debug/dbtest`
fish: Job 1, 'cargo run' terminated by signal SIGSEGV (Address boundary error)
```
